name: master

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.13', '1.12' ]
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: diff -u <(echo -n) <(gofmt -d ./)
    - run: go get honnef.co/go/tools/cmd/staticcheck && staticcheck github.com/nazo/lunchbox
    - run: go test ./...